
###
POST http://localhost:3000/api/v1/accommodations
Content-Type: application/json

{
    "title": "Hermosa casa en la playa2",
    "description": "Casa con vista al mar y todas las comodidades.",
    "rules": "No se permiten fiestas",
    "accommodationType": "House",
    "nightPrice": 150,
    "guestsNumber": 4,
    "roomsNumber": 2,
    "bedsNumber": 3,
    "bathroomsNumber": 2,
    "accommodationServices": ["internet", "parking", "pool"],
    "location": {
        "latitude": 20.659698,
        "longitude": -103.349609
    },
    "userId": "66469fbc6f5d4fd22a3861a7"
}