
###
POST http://localhost:3000/api/v1/bookings
Content-Type: application/json

{
    "accommodationId": "664a39db2ca2022d8b1c1789",
    "beginningDate": "2024-05-20T00:00:00.000Z", 
    "endingDate": "2024-05-25T00:00:00.000Z",
    "numberOfGuests" : 2, 
    "totalCost": 200.00, 
    "bookingStatus": "Current",
    "guestUser": "66469fbc6f5d4fd22a3861a7", 
    "hostUser": "6646a151227900e638acafa0"     
}
