### GET USER BY ID
GET http://localhost:3000/api/v1/users/66469fbc6f5d4fd22a3861a7


###

POST http://localhost:3000/api/v1/auth/signup
Content-Type: application/json

{
    "email": "eduardo1@gmail.com",
    "fullName": "Eduardo Garcia Diaz",
    "birthDate": "2024-02-02",
    "phoneNumber": "2288304609",
    "password": "Eduardo_11"
}

### USUARIO 2

POST http://localhost:3000/api/v1/auth/signup
Content-Type: application/json

{
    "email": "daniel@gmail.com",
    "fullName": "Daniel Arcos",
    "birthDate": "2024-05-05",
    "phoneNumber": "2288304569",
    "password": "12345"
}

###

PUT http://localhost:3000/api/v1/users/66467c2bdc480001e4adc8bb
Content-Type: application/json

{
    "email": "eduardo@gmail.com",
    "fullName": "Eduardo Garcia Diaz",
    "birthDate": "2024-02-02",
    "phoneNumber": "2288304609",
    "occupation" : "Ingeniero de Software",
    "residence" : "Xalapa"
}

###
DELETE http://localhost:3000/api/v1/users/6645449210d8a1bdc50db189
Content-Type: application/json

{
    "password": "12345"
}

